[package]
name = "wasm_fractal"
version = "0.1.0"
authors = ["Marko Stevanović <stevanovicmarko@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
num-complex = "0.2.0"
image = "0.19.0"
